### ISSUE TITLE
How to handle closed polls.

### ISSUE THREAD

**Issue by longtomjr** [SpaceKrakens/Ranked-Vote#24]
This issue is to discuss what direction we want to take.
### Questions that need some discussion:
1. How should we handle closing a poll, functionally?
2. Should we allow re-opening polls, and what will be the limitations?
3. Should we allow cloning?
4. If we allow cloning, should we only allow it to be done by server admins?
5. Should cloning create an empty (no votes added) poll, or clone the poll with all the votes?

### Points already made (thanks to @BraedonWooding):
- Re-opening polls can be useful, but it might be better to only do that through cloning.
- Re-opening a closed poll can be seen as undemocratic.
- Cloning will solve the problem of Re-Opening, since the original will not be touched.
- Cloning to an empty instance of a poll would open the door for reruns - which could be considered undemocratic.
- Cloning might be a useful tool "behind the scenes."

**Comment by powli** [comment]
Closed polls in the poll list should have their main action (standard: vote) be changed to result view. An additional action for viewing just your own vote should be also present. The voting page will have a message stating that the poll is closed and voting is no longer possible - submit button should be either disabled or not rendered.

On the poll create post route we have to add a sanity check for the polls closing date (so you can no longer edit your vote on closed polls by forging the request).

I'm against any form of reopening or cloning for a poll - I don't see a value, because once a poll is closed, it's done - a consens has been found, a winner chosen - whatever. Reopening or cloning sounds really strong like "Well I don't like the polls result, let's redo them!". You can't vote on your government after election day either!

If the feature gets requested, we might think about it again, but I definitely don't see it in MVP/0.1, since you are technically able to just create a new poll with the same (or better: updated) options.

**Comment by longtomjr** [comment]
### Todo:
- [ ] Result view (see #15 )
- [ ] Create a sanity check on the post route of closed polls. (To disable editing and adding vote results by posting data to the server).
- [ ] Disable the voting form to be altered and posted. - Using the voting form to display the user's vote.

**Comment by BraedonWooding** [comment]
On the idea of Result view, how are we thinking of displaying it?  You mentioned a widget, can you elaborate on what you are thinking of it looking like?
